/**
 * Download multiple optimized images as ZIP
 * Supports both Vercel (/tmp) and local (public) storage
 */
import archiver from 'archiver';
import fs from 'fs';
import path from 'path';

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { filenames } = req.body;

    if (!filenames || !Array.isArray(filenames) || filenames.length === 0) {
      return res.status(400).json({ error: 'Filenames array is required' });
    }

    // Limit to 50 files
    if (filenames.length > 50) {
      return res.status(400).json({ 
        error: 'Maximum 50 files allowed',
        received: filenames.length 
      });
    }

    // Determine output directory based on environment
    const OUTPUT_DIR = process.env.VERCEL ? '/tmp/optimized' : './public/images/optimized';

    // Set response headers for ZIP download
    const timestamp = Date.now();
    const zipFilename = `optimized-images-${timestamp}.zip`;
    
    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', `attachment; filename="${zipFilename}"`);
    res.setHeader('Cache-Control', 'no-cache');

    // Create ZIP archive
    const archive = archiver('zip', {
      zlib: { level: 9 } // Maximum compression
    });

    // Handle archive errors
    archive.on('error', (err) => {
      console.error('Archive error:', err);
      throw err;
    });

    // Pipe archive to response
    archive.pipe(res);

    // Add files to archive
    let addedCount = 0;
    let errorCount = 0;

    for (const filename of filenames) {
      try {
        // Sanitize filename
        const safeName = path.basename(filename);
        const filePath = path.join(OUTPUT_DIR, safeName);

        // Check if file exists
        if (fs.existsSync(filePath)) {
          // Add file to archive
          archive.file(filePath, { name: safeName });
          addedCount++;
        } else {
          console.warn(`File not found: ${safeName}`);
          errorCount++;
        }
      } catch (error) {
        console.error(`Error adding file ${filename}:`, error);
        errorCount++;
      }
    }

    // If no files were added, return error
    if (addedCount === 0) {
      archive.abort();
      return res.status(404).json({ 
        error: 'No files found',
        message: 'None of the requested files exist'
      });
    }

    // Add a summary text file
    const summary = `Image Optimization Summary
========================

Total Files: ${addedCount}
Failed: ${errorCount}
Timestamp: ${new Date().toISOString()}

Generated by Image Optimizer Professional Edition
https://image-optimizer.rochiyat.my.id
`;

    archive.append(summary, { name: 'README.txt' });

    // Finalize archive
    await archive.finalize();

    console.log(`ZIP created: ${addedCount} files, ${errorCount} errors`);

  } catch (error) {
    console.error('Download ZIP error:', error);
    
    // If headers not sent yet, send error response
    if (!res.headersSent) {
      return res.status(500).json({ 
        error: 'Failed to create ZIP',
        message: error.message 
      });
    }
  }
}
